//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Core
{
    [Serializable]
    public class GoalMsg : Message
    {
        public const string k_RosMessageName = "core_msgs/Goal";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public Geometry.PoseMsg pose;
        public string id;
        public string name;
        public string type;

        public GoalMsg()
        {
            this.header = new HeaderMsg();
            this.pose = new Geometry.PoseMsg();
            this.id = "";
            this.name = "";
            this.type = "";
        }

        public GoalMsg(HeaderMsg header, Geometry.PoseMsg pose, string id, string name, string type)
        {
            this.header = header;
            this.pose = pose;
            this.id = id;
            this.name = name;
            this.type = type;
        }

        public static GoalMsg Deserialize(MessageDeserializer deserializer) => new GoalMsg(deserializer);

        private GoalMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.id);
            deserializer.Read(out this.name);
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pose);
            serializer.Write(this.id);
            serializer.Write(this.name);
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "GoalMsg: " +
            "\nheader: " + header.ToString() +
            "\npose: " + pose.ToString() +
            "\nid: " + id.ToString() +
            "\nname: " + name.ToString() +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
