// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: MonitorMessageV2.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace WebSocketClient
{
    [global::ProtoBuf.ProtoContract()]
    public partial class Point : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Changeness : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string objectID { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Point Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"movement")]
        public Point Movement { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InitializeEnvironment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string environmentID { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"objects")]
        public global::System.Collections.Generic.List<VirtualObject> Objects { get; } = new global::System.Collections.Generic.List<VirtualObject>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VirtualObject : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string objectID { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"position")]
        public Point Position { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"property")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Properties { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DumpEnvironment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string environmentID { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"objects")]
        public global::System.Collections.Generic.List<ModifiedVirtualObject> Objects { get; } = new global::System.Collections.Generic.List<ModifiedVirtualObject>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModifiedVirtualObject : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string objectID { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"position")]
        public Point Position { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public float orientationAngle { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimulationCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Command command { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string environmentID { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public enum Command
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CREATE")]
            Create = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"START")]
            Start = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"RESUME")]
            Resume = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"PAUSE")]
            Pause = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"STOP")]
            Stop = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"DELETE")]
            Delete = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EventGenerate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
